exchanges:
  Conductivity:
    name: "conductivity"
    message_type: "ConductivityData"

  APC:
    name: "apc"
    message_type: "APCData"

  SITA:
    name: "sita"
    message_type: "SITAData"

  ADS_Values:
    name: "ads_values"
    message_type: "PDB_State"

  PDB_Service_Requests:
    name: "pdb_service_requests"
    message_type: "PDB_ServiceRequest"

  PDB_Service_Responses:
    name: "pdb_service_responses"
    message_type: "PDB_ServiceResponse"


nodes:
  conductivity:
    serial_port: "/dev/serial/by-id/usb-UTEK_USB__-__Serial_Converter_FT9EJUZ4-if00-port0"
    baudrate: 9600
    read_timeout: 120.0 # Seconds
    publish_exchange: "Conductivity"

  apc:
    serial_port: "/dev/serial/by-id/usb-UTEK_USB__-__Serial_Converter_FT9EJUZ4-if01-port0"
    baudrate: 9600 
    read_timeout: 120.0 # Seconds
    publish_exchange: "APC"

  sita:
    serial_port: "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AK06HO0D-if00-port0"
    baudrate: 57600
    sample_read_interval: 120.0 # Seconds
    serial_read_timeout: 1.0
    measure_time_limit: 30.0 # Seconds
    publish_exchange: "SITA"

  recorder:
    output_dir: "/mnt/hydra_data"
    subscribe_exchanges:
      - "Conductivity"
      - "APC"
      - "SITA"
      - "ADS_Values"

  pdb_controller:
    # ADS addresses are defined in pdb_pins.yaml
    mcp_address: 0x20
    ads_ratio: 11.060 # Original code has 24/2.17 as a default
    ads_interval: 60.0 # Seconds
    publish_exchange: "ADS_Values"
    service_request_exchange: "PDB_Service_Requests"
    service_response_exchange: "PDB_Service_Responses"

  supervisor:
    service_request_exchange: "PDB_Service_Requests"    
    service_response_exchange: "PDB_Service_Responses"

  user:
    service_request_exchange: "PDB_Service_Requests"    
    service_response_exchange: "PDB_Service_Responses"
    
  starlink:
    service_request_exchange: "PDB_Service_Requests"    
    service_response_exchange: "PDB_Service_Responses"

  heartbeat:
    high_time: 1.0 # Seconds
    low_time: 5.0 # Seconds

  # user:
  #   publish_exchanges:
  #     - 
  #   subscribe_exchanges:
  #     - 
