exchanges:
  conductivity:
    name: "conductivity"
    message_type: "SensorData"

  apc:
    name: "apc"
    message_type: "SensorData"

  sita:
    name: "sita"
    message_type: "SensorData"

  mcp_commands:
    name: "mcp_commands"
    message_type: "PDB_Command"

  ads_values:
    name: "ads_values"
    message_type: "PDB_State"

nodes:
  conductivity:
    serial_port: "/dev/ttyUSB1"
    baudrate: 9600
    read_timeout: 5.0
    publish_exchange: "conductivity"

  apc:
    serial_port: "/dev/ttyUSB2"
    baudrate: 9600 
    read_timeout: 5.0
    publish_exchange: "apc"

  sita:
    serial_port: "/dev/ttyUSB2"
    baudrate: 19200
    read_timeout: 5.0
    publish_exchange: "sita"

  recorder:
    output_dir: "/mnt/hydra_data"
    subscribe_exchanges:
      - "conductivity"
      # - "apc"
      # - "sita"

  pdb_controller:
    ads_addresses:
      - 0x48
      - 0x49
      - 0x4A
      - 0x4B
    mcp_address: 0x20
    ads_ratio: 11.060 # Original code has 24/2.17 as a default
    publish_exchange: "ads_values"
    subscribe_exchange: "mcp_commands"

  supervisor:
    publish_exchange: "mcp_commands"
    subscribe_exchanges: "ads_values"

  # user:
  #   publish_exchanges:
  #     - 
  #   subscribe_exchanges:
  #     - 
